name: ci-cd

on: [push, pull_request]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - "3.10"
          - "3.11"
          
    name: Test
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      # Etape pour construire l'image Docker
      - name: Build Docker image
        run: docker build -t myfirstpythonapp .

      # Etape pour tester si le conteneur Docker fonctionne
      - name: Test Docker container
        run: |
          docker run -d --name mycontainer -p 5000:5000 myfirstpythonapp
          # Attendre que le serveur web dans le conteneur soit accessible
          docker ps
          # Vérifier si le serveur est accessible sur le port 5000
          curl http://localhost:5000 || exit 1
          # Nettoyer le conteneur après le test
          docker rm -f mycontainer
